SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";


CREATE TABLE IF NOT EXISTS `JOB` (
    `ID` varchar(3) NOT NULL,
    `JobType` char(20) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


/*ALTER TABLE `EMPLOYEE`
 ADD PRIMARY KEY (``);*/
 
 