SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";



CREATE TABLE IF NOT EXISTS `REGISTRATION` (
`CustID` int(3) NOT NULL,
  `username` varchar(20) NOT NULL,
  `Password` varchar(20) NOT NULL,
    `Email` varchar(30) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


ALTER TABLE `REGISTRATION`
 ADD PRIMARY KEY (`CustID`);


ALTER TABLE `REGISTRATION`
MODIFY `CustID` int(3) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1;

